# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84c75d7eecdbacea1b9007f3c2c78a8b7868cf786186351c1a3ff73871376edcbf9b6ab80c81ceb6f8f98c9a4b88eed1d730e18afe58c49f15d800873a96031f

test:
  secret_key_base: a531763a89313c92800a5278a0698d4dd227be53e73d6bb9a1a8cf8002347ddd8554daeb48810a462ede063f29a35ebcce6ea0af0641968bbdca83d2b8dd1db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
